name := "implicit-collector"
version := "0.1"
scalaVersion := "2.12.3"
libraryDependencies += "org.scalameta" %% "testkit" % "2.0.0-M3"
scalacOptions += "-Yno-adapted-args"
assemblyJarName in assembly := "implicit-collector.jar"